---
# Example config file
pubNubUser: "test_listener"             # Subscriber username
pubNubSubscribeKey: "sub-key-text"      # Replace with Subscriber key text
cursor: 17392513309612033      # Optional parameter to grab history if needed
pubNubSubscriptions:
- channelName: "Channel1"      # First channel name to connect to
  receivePresenceEvents: false # Turn on / off PresenceEvents from channel
- channelName: "Channel2"
  receivePresenceEvents: false
- channelName: "Channel3"
  receivePresenceEvents: false
